---
- name: Ensure sshd is present in Arch distros
  pacman:
    name: openssh
    state: present
  become: true
  when: ansible_os_family == 'Archlinux'

- name: Ensure sshd is present in Debian distros
  apt:
    name: openssh-server
    state: present
  become: true
  when: ansible_os_family == 'Debian'

- name: Ensure wheel group exists
  group:
    name: wheel
    state: present
  become: true

- name: Create primary unprivileged user account
  user:
    name: "{{ ssh_user_username }}"
    password: "{{ ssh_user_password }}"
    group: users
    groups: wheel
    append: true
    shell: /bin/zsh
    generate_ssh_key: true
  become: true

- name: Ensure .ssh directory exists
  file:
    dest: ~/.ssh
    state: directory
    mode: 0700
    owner: "{{ ssh_user_username }}"
  become: true
  become_user: "{{ ssh_user_username }}"

- name: Add authorized keys to primary unprivileged user account
  authorized_key:
    user: "{{ ssh_user_username }}"
    key: "{{ item }}"
    state: present
  with_items: "{{ ssh_user_pub_keys }}"

- name: Add known host pub keys to primary unprivileged user account
  template:
    src: .ssh/known_hosts.j2
    dest: ~/.ssh/known_hosts
    force: false
  become: true
  become_user: "{{ ssh_user_username }}"
